/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.connectjob.gui;

import grpc.generated.job.AddJobResponse;
import distsys.connectjob.job.JobClient;
import grpc.generated.job.Job;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import distsys.connectjob.candidate.CandidateClient;
import grpc.generated.candidate.CandidateResponse;
import grpc.generated.candidate.SkillSummary;

/**
 * ConnectJobInterface.java
 * @author Nailton Batista
 * Version 1.0
 * 12/07/2026
 */
public class ConnectJobInterface extends javax.swing.JFrame {
    
    private JobClient jobClient; //JobClient variable
    private CandidateClient candidateClient; //CandidateClient variable
    private final List<String> candidateSkills = new ArrayList<>(); //temporary list
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConnectJobInterface.class.getName());

    /**
     * Creates new form ConnectJobInterface
     */
    public ConnectJobInterface() {
        initComponents();
        connectToJobService();
        connectToCandidateService();
    }
    
    //Creating connection with the JobService
    private void connectToJobService() {

        try {

            jobClient = new JobClient();

            JOptionPane.showMessageDialog(this,"JobService connected successfully.");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,"Could not connect to JobService:\n"+ e.getMessage());
            
            //deactivating all btn if service is not found
            btnAddJob.setEnabled(false);
            btnSearchJobs.setEnabled(false);
        }
    }

    //Creating a connection between CandidateClient and CandidateService
   private void connectToCandidateService() {

       try {

           candidateClient = new CandidateClient();

           JOptionPane.showMessageDialog(this, "CandidateService connected successfully.");

       } catch (Exception e) {

           JOptionPane.showMessageDialog( this, "Could not connect to CandidateService:\n" + e.getMessage(), "Connection error", JOptionPane.ERROR_MESSAGE);

           //deactivating all btn if service is not found
           btnRegisterCandidate.setEnabled(false);
           btnAddSkill.setEnabled(false);
           btnUploadSkills.setEnabled(false);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtJobId = new javax.swing.JTextField();
        txtJobTitle = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        txtJobLocation = new javax.swing.JTextField();
        txtJobDescription = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        btnAddJob = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSearchJobTitle = new javax.swing.JTextField();
        txtSearchJobLocation = new javax.swing.JTextField();
        btnSearchJobs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJobResults = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCandidateId = new javax.swing.JTextField();
        txtCandidateName = new javax.swing.JTextField();
        txtCandidateEmail = new javax.swing.JTextField();
        btnRegisterCandidate = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSkillCandidateId = new javax.swing.JTextField();
        txtSkillName = new javax.swing.JTextField();
        btnAddSkill = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCandidateSkills = new javax.swing.JTextArea();
        btnUploadSkills = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtInterviewId = new javax.swing.JTextField();
        txtInterviewCandidateId = new javax.swing.JTextField();
        txtInterviewJobId = new javax.swing.JTextField();
        txtInterviewDate = new javax.swing.JTextField();
        txtInterviewTime = new javax.swing.JTextField();
        btnScheduleInterview = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtChatSender = new javax.swing.JTextField();
        txtChatMessage = new javax.swing.JTextField();
        btnSendMessage = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtChatMessages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ConnectJob");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setText("Company name:");

        jLabel2.setText("Job title:");

        jLabel1.setText("Job ID:");

        jLabel4.setText("Job location:");

        jLabel5.setText("Job description:");

        jLabel6.setText("Annual salary:");

        btnAddJob.setBackground(new java.awt.Color(0, 204, 51));
        btnAddJob.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddJob.setForeground(new java.awt.Color(0, 0, 0));
        btnAddJob.setText("ADD JOB");
        btnAddJob.addActionListener(this::btnAddJobActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddJob)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtJobTitle)
                        .addComponent(txtCompanyName)
                        .addComponent(txtJobLocation)
                        .addComponent(txtJobDescription)
                        .addComponent(txtSalary)
                        .addComponent(txtJobId, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(300, 300, 300))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJobLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJobDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddJob)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Job", jPanel4);

        jLabel7.setText("Job title:");

        jLabel8.setText("Job location:");

        btnSearchJobs.setBackground(new java.awt.Color(0, 204, 51));
        btnSearchJobs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSearchJobs.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchJobs.setText("SEARCH JOBS");
        btnSearchJobs.addActionListener(this::btnSearchJobsActionPerformed);

        txtJobResults.setEditable(false);
        txtJobResults.setColumns(20);
        txtJobResults.setLineWrap(true);
        txtJobResults.setRows(5);
        txtJobResults.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtJobResults);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchJobs)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSearchJobTitle)
                                .addComponent(txtSearchJobLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearchJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSearchJobLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearchJobs)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Search Jobs", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Jobs", jPanel1);

        jLabel9.setText("Candidate ID:");

        jLabel10.setText("Name:");

        jLabel11.setText("Email:");

        btnRegisterCandidate.setBackground(new java.awt.Color(0, 204, 51));
        btnRegisterCandidate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegisterCandidate.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterCandidate.setText("REGISTER CANDIDATE");
        btnRegisterCandidate.addActionListener(this::btnRegisterCandidateActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisterCandidate)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCandidateId)
                        .addComponent(txtCandidateName)
                        .addComponent(txtCandidateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCandidateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCandidateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCandidateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegisterCandidate)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Register Candidate", jPanel7);

        jLabel12.setText("Candidate ID:");

        jLabel13.setText("Skill:");

        btnAddSkill.setBackground(new java.awt.Color(0, 204, 51));
        btnAddSkill.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddSkill.setForeground(new java.awt.Color(0, 0, 0));
        btnAddSkill.setText("ADD SKILL");
        btnAddSkill.addActionListener(this::btnAddSkillActionPerformed);

        txtCandidateSkills.setEditable(false);
        txtCandidateSkills.setColumns(20);
        txtCandidateSkills.setLineWrap(true);
        txtCandidateSkills.setRows(5);
        txtCandidateSkills.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtCandidateSkills);

        btnUploadSkills.setBackground(new java.awt.Color(0, 204, 51));
        btnUploadSkills.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUploadSkills.setForeground(new java.awt.Color(0, 0, 0));
        btnUploadSkills.setText("UPLOAD SKILLS");
        btnUploadSkills.addActionListener(this::btnUploadSkillsActionPerformed);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddSkill)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSkillCandidateId)
                                .addComponent(txtSkillName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnUploadSkills)))
                .addGap(280, 280, 280))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSkillCandidateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSkillName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddSkill)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUploadSkills)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Upload Skills", jPanel8);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Candidates", jPanel2);

        jLabel14.setText("Interview ID:");

        jLabel15.setText("Candidate ID:");

        jLabel16.setText("Job ID:");

        jLabel17.setText("Date:");

        jLabel18.setText("Time:");

        btnScheduleInterview.setBackground(new java.awt.Color(0, 204, 51));
        btnScheduleInterview.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnScheduleInterview.setForeground(new java.awt.Color(0, 0, 0));
        btnScheduleInterview.setText("SCHEDULE INTERVIEW");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(48, 48, 48)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnScheduleInterview)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtInterviewId)
                        .addComponent(txtInterviewCandidateId)
                        .addComponent(txtInterviewJobId)
                        .addComponent(txtInterviewDate)
                        .addComponent(txtInterviewTime, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(277, 277, 277))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtInterviewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtInterviewCandidateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtInterviewJobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtInterviewDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtInterviewTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnScheduleInterview)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Schedule Interview", jPanel9);

        jLabel19.setText("Sender:");

        jLabel20.setText("Message:");

        btnSendMessage.setBackground(new java.awt.Color(0, 204, 51));
        btnSendMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSendMessage.setForeground(new java.awt.Color(0, 0, 0));
        btnSendMessage.setText("SEND");

        txtChatMessages.setEditable(false);
        txtChatMessages.setColumns(20);
        txtChatMessages.setLineWrap(true);
        txtChatMessages.setRows(5);
        txtChatMessages.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtChatMessages);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendMessage)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtChatSender)
                                .addComponent(txtChatMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtChatSender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtChatMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSendMessage)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );

        jTabbedPane4.addTab("Interview Chat", jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4))
        );

        jTabbedPane1.addTab("Interviews", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJobActionPerformed
        // TODO add your handling code here:
        try {

            int jobId = Integer.parseInt(
                    txtJobId.getText().trim()
            );

            double salary = Double.parseDouble(
                    txtSalary.getText().trim()
            );

            AddJobResponse response = jobClient.addJob(
                    jobId,
                    txtJobTitle.getText(),
                    txtCompanyName.getText(),
                    txtJobLocation.getText(),
                    txtJobDescription.getText(),
                    salary
            );

            JOptionPane.showMessageDialog(this,response.getMessage());

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,"Job ID and salary must be numeric.");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnAddJobActionPerformed

    private void btnSearchJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchJobsActionPerformed
        // TODO add your handling code here:
        try {

        List<Job> jobs = jobClient.searchJobPosition(
                txtSearchJobTitle.getText(),
                txtSearchJobLocation.getText()
        );

        txtJobResults.setText("");

        if (jobs.isEmpty()) {

            txtJobResults.setText("No matching jobs were found.");

            return;
        }

        StringBuilder result = new StringBuilder();

        for (Job job : jobs) {

            result.append("----------------------\n");
            result.append("ID: ").append(job.getJobId()).append("\n");

            result.append("Title: ").append(job.getJobTitle()).append("\n");

            result.append("Company: ").append(job.getCompanyName()).append("\n");

            result.append("Location: ").append(job.getJobLocation()).append("\n");

            result.append("Description: ").append(job.getJobDescription()).append("\n");

            result.append("Salary: €").append(job.getSalary()).append("\n\n");
        }

        txtJobResults.setText(result.toString());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnSearchJobsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (jobClient != null) {
            jobClient.shutdown();
        }
        if (candidateClient != null) {
            candidateClient.shutdown();
        }

        /*if (interviewClient != null) {
            interviewClient.shutdown();
        }*/
    }//GEN-LAST:event_formWindowClosing

    private void btnRegisterCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCandidateActionPerformed
        // TODO add your handling code here:
        if (candidateClient == null) {

        JOptionPane.showMessageDialog(
                this,
                "CandidateService is not connected.",
                "Connection error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
        }

        try {

            //calling the unary rpc 'RegisterCandidate
            CandidateResponse response = candidateClient.registerCandidate(
                            txtCandidateId.getText(),
                            txtCandidateName.getText(),
                            txtCandidateEmail.getText());

            JOptionPane.showMessageDialog(
                    this,
                    response.getMessage(),
                    response.getSuccess() ? "Candidate was registered" : "Candidate was not registered",
                    response.getSuccess() ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.WARNING_MESSAGE);

            //getting the fields empty when candidate's skill is successfully registered
            if (response.getSuccess()) {

                txtCandidateId.setText("");
                txtCandidateName.setText("");
                txtCandidateEmail.setText("");

                txtCandidateId.requestFocus();
            }

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this,e.getMessage(),"The data inserted is invalid",JOptionPane.WARNING_MESSAGE );

        } catch (RuntimeException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "Remote service error", JOptionPane.ERROR_MESSAGE );}
        
    }//GEN-LAST:event_btnRegisterCandidateActionPerformed

    private void btnAddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSkillActionPerformed
        // TODO add your handling code here:
         String skillName = txtSkillName.getText().trim();

        //Making sure that no empty skill will be submitted
        if (skillName.isBlank()) {

            JOptionPane.showMessageDialog(this,"Please enter a skill.","The skill is invalid",JOptionPane.WARNING_MESSAGE);

            return;
        }

        //Adding the skill to a temporary list of the interface
        candidateSkills.add(skillName);

        //Just displaying the skill on the text area
        txtCandidateSkills.append(
                skillName + "\n"
        );


        //cleaning the field for next skill
        txtSkillName.setText("");
        txtSkillName.requestFocus();
    }//GEN-LAST:event_btnAddSkillActionPerformed

    private void btnUploadSkillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadSkillsActionPerformed
        // TODO add your handling code here:
        if (candidateClient == null) {

            JOptionPane.showMessageDialog( this, "CandidateService isn't connected.", "Connection error", JOptionPane.ERROR_MESSAGE);

            return;
        }

        try {

            //Calling for UploadSkill
            SkillSummary summary = candidateClient.uploadSkills( txtSkillCandidateId.getText(), candidateSkills);

            JOptionPane.showMessageDialog(this, summary.getMessage() + 
                    "\nCandidate ID: " + summary.getCandidateId() + 
                    "\nTotal skills: " + summary.getTotalSkills(), "Skill was upload result",
                    JOptionPane.INFORMATION_MESSAGE );

            //Emptying the field if everything goes well
            candidateSkills.clear();

            txtCandidateSkills.setText("");
            txtSkillName.setText("");
            txtSkillCandidateId.setText("");

            txtSkillCandidateId.requestFocus();

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog( this, e.getMessage(), "The data inserted is invalid", JOptionPane.WARNING_MESSAGE);

        } catch (RuntimeException e) {

            JOptionPane.showMessageDialog( this, e.getMessage(), "Error with the remote service.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUploadSkillsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConnectJobInterface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJob;
    private javax.swing.JButton btnAddSkill;
    private javax.swing.JButton btnRegisterCandidate;
    private javax.swing.JButton btnScheduleInterview;
    private javax.swing.JButton btnSearchJobs;
    private javax.swing.JButton btnSendMessage;
    private javax.swing.JButton btnUploadSkills;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField txtCandidateEmail;
    private javax.swing.JTextField txtCandidateId;
    private javax.swing.JTextField txtCandidateName;
    private javax.swing.JTextArea txtCandidateSkills;
    private javax.swing.JTextField txtChatMessage;
    private javax.swing.JTextArea txtChatMessages;
    private javax.swing.JTextField txtChatSender;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtInterviewCandidateId;
    private javax.swing.JTextField txtInterviewDate;
    private javax.swing.JTextField txtInterviewId;
    private javax.swing.JTextField txtInterviewJobId;
    private javax.swing.JTextField txtInterviewTime;
    private javax.swing.JTextField txtJobDescription;
    private javax.swing.JTextField txtJobId;
    private javax.swing.JTextField txtJobLocation;
    private javax.swing.JTextArea txtJobResults;
    private javax.swing.JTextField txtJobTitle;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearchJobLocation;
    private javax.swing.JTextField txtSearchJobTitle;
    private javax.swing.JTextField txtSkillCandidateId;
    private javax.swing.JTextField txtSkillName;
    // End of variables declaration//GEN-END:variables
}
